### ISSUE TITLE
 It may be incompatible with "BunkbedRevive".

### ISSUE THREAD

**Issue by rainbow137** [Lauriichan/LC-FriendPatches#3]
### Mod version

1.0.1

### Mod list

https://thunderstore.io/c/lethal-company/p/ViViKo/BunkbedRevive/

### Describe what happend

When a player revives a dead teammate by carrying their body, the revived teammate may remain in spectator mode even after being revived, or they may freeze in place or experience a black screen.

### Reproduction steps

Using the corresponding module can reproduce this issue.

### Expected behavior

freezing of perspective，black screen

**Comment by Lauriichan** [comment]
Did you try to use the mod without FriendPatches installed?

**Comment by Lauriichan** [comment]
I can't really see a reason why the mentioned mod should not work with FriendPatches

EDIT: After checking the decompiled source of BunkbedRevive thoroughly I was unable to find anything that could conflict with FriendPatches or the other way around. Maybe I am unable to see the issue because I don't have the actual source code of BunkbedRevive and just a decompiled version of it but all in all I don't think this is the case here.

All FriendPatches does is patch the join callback of LethalCompany and then log the player once they joined. Another thing it does is listen to steam persona update events and then update players names accordingly.

It never modifies anything else on any player and is a clientside mod so it should not interfere with any RPC calls.

**Comment by Lauriichan** [comment]
Also you might want to try and update the mod

**Comment by Lauriichan** [comment]
This might be related to #1.

**Comment by Lauriichan** [comment]
Might have been fixed with 6b3acbd (1.0.2)

**Comment by rainbow137** [comment]
Thank you very much for your reply, it may be my other mods that are causing the conflict (there are currently more than two hundred in total), I will try the new version (1.0.2) and hopefully it will be fixed

**Comment by rainbow137** [comment]
> Might have been fixed with [6b3acbd](https://github.com/Lauriichan/LC-FriendPatches/commit/6b3acbdced40898b6c51a57e8f01a4c0b88f0543) (1.0.2)

After testing with my friends and me, version 1.0.2 doesn't seem to solve the staging problem

**Comment by Lauriichan** [comment]
Could you try to disable the the Played With feature and see if that fixed it and if it didn't to try and disable the name fix feature.
You can do so in the config of the mod.
This might get some clues about what is going on there.
Also could you provide a full mod list (if you are not just using BunkbedRevive), to do so just follow these instructions:

If you are using Thunderstore Mod Manager or r2modmanager you can get a full list like this:

1. Go into the Settings of your profile.
2. Click on the 'Modpacks' tab.
3. Click on 'Show dependency strings'.
4. Copy the content of the dialog and paste it here.

If you are not using Thunderstore or the r2modmanager it would be appreciated if you could list the mods in a similar fashion (name + version) or link to the mod with the version of the mod.
Thank you in advance!

**Comment by Lauriichan** [comment]
I will close this issue as I think this is related to #1, please provide the requested information there instead of this issue, thank you :)
